var availableProducts = [
	{
		id: 0,
		category: "electronics",
		price: 30.0,
		productName: "HP Laptop",
		image: "../assets/images/laptop.jpg",
		inCart: 0,
	},
	{
		id: 1,
		category: "food",
		price: 100.0,
		productName: "Hamburger",
		image: "../assets/images/hamburger.jpeg",
		inCart: 0,
	},
	{
		id: 2,
		category: "sports",
		price: 10.0,
		productName: "Ball",
		image: "../assets/images/ball.jpeg",
		inCart:  0,
	},
	{
		id: 3,
		category: "drink",
		price: 5.99,
		productName: "Orange Juice",
		image: "../assets/images/orange.jpeg",
		inCart:  0,
	},
	{
		id: 4,
		category: "electronics",
		price: 300.0,
		productName: "Mobile",
		image: "../assets/images/mobile.jpeg",
		inCart:  0,
	},
	{
		id: 5,
		category: "food",
		price: 130.0,
		productName: "Steak",
		image: "../assets/images/steak.jpeg",
		inCart:  0,
	},
	{
		id: 6,
		category: "sports",
		price: 35.0,
		productName: "Basket Ball",
		image: "../assets/images/basketball.jpeg",
		inCart:  0,
	},
	{
		id: 7,
		category: "fruit",
		price: 20.0,
		productName: "Pineapple",
		image: "../assets/images/pineapple.jpeg",
		inCart:  0,
	},
];
